### ISSUE TITLE
Path's with Spaces

### ISSUE THREAD

**Issue by DcmanProductions** [huntercfreeman/dotnetSolutionExplorer#6]
# Overview
It seems that if the path to the .sln file has a space in it, the extension either fully breaks, or won't let you open any files.

**Comment by huntercfreeman** [comment]
Hey.

I made https://github.com/huntercfreeman/dot-net-ide as a replacement
Visual Studio Code extension.

It contains an updated Solution Explorer and a Nuget Package Manager.

When I get the time I should change the README.md for the older version
under a different repo.

I cloned the newer source code and could not replicate the issue of path's
with spaces.

Here is a link directly to the newer extension:

https://marketplace.visualstudio.com/items?itemName=HunterFreeman.dot-net-ide

**Comment by DcmanProductions** [comment]
Thank you
